import json

tr_translations = {
    "Accommodation": "Konaklama",
    "Tourist Trips": "Turistik Geziler",
    "Once submitted, one of our consultants will contact you within 24 hours.": "Gönderildikten sonra, danışmanlarımızdan biri 24 saat içinde sizinle iletişime geçecektir.",
    "Customize Tourism Services": "Turizm Hizmetlerini Özelleştir",
    "Required Destinations (You can select multiple cities)": "Gerekli Destinasyonlar (Birden fazla şehir seçebilirsiniz)",
    "Plan Your Luxury Trip": "Lüks Seyahatinizi Planlayın",
    "We design exceptional travel experiences that exceed your expectations, where luxury meets authenticity in the heart of Turkey.": "Beklentilerinizi aşan, lüksün otantiklikle buluştuğu Türkiye'nin kalbinde olağanüstü seyahat deneyimleri tasarlıyoruz.",
    "Number of Travelers": "Yolcu Sayısı",
    "Adults": "Yetişkin",
    "Children": "Çocuk",
    "Submit Inquiry": "Talebi Gönder",
    "Istanbul": "İstanbul",
    "Trabzon": "Trabzon",
    "Add City": "Şehir Ekle",
    "Customize Your Journey": "Seyahatinizi Özelleştirin",
    "Destinations": "Destinasyonlar",
    "Travelers": "Yolcular",
    "Services": "Hizmetler",
    "Click \"Add City\" to start building your route...": "Rotanızı oluşturmaya başlamak için \"Şehir Ekle\"ye tıklayın...",
    "Trip Start": "Seyahat Başlangıcı",
    "Trip End": "Seyahat Bitişi",
    "Who are you traveling with?": "Kiminle seyahat ediyorsunuz?",
    "years": "yaş",
    "Please provide children ages": "Lütfen çocukların yaşlarını belirtin",
    "Custom Services": "Özel Hizmetler",
    "Flights": "Uçuşlar",
    "Accommodation Style": "Konaklama Tarzı",
    "Modern Hotel": "Modern Otel",
    "Family Apartment": "Aile Apartmanı",
    "Rustic Cottage": "Rustik Kır Evi",
    "Group Type": "Grup Tipi",
    "Private (VIP)": "Özel (VIP)",
    "Standard Group": "Standart Grup",
    "Back": "Geri",
    "Next Step": "Sonraki Adım",
    "Finish and Send Inquiry": "Bitir ve Talebi Gönder",
    "A travel consultant will reach out via WhatsApp within 24 hours.": "Bir seyahat danışmanı 24 saat içinde WhatsApp üzerinden size ulaşacaktır.",
    "An error occurred.": "Bir hata oluştu.",
    "Explore our carefully curated tourist trips": "Özenle seçilmiş turistik gezilerimizi keşfedin",
    "What is included": "Neler dahil",
    "What to bring / Remarks": "Ne getirmeli / Notlar",
    "Book Now": "Şimdi Rezervasyon Yap",
    "Trip": "Seyahat",
    "Featured Programs": "Öne Çıkan Programlar",
    "Discover our most popular travel packages based on customer visits": "Müşteri ziyaretlerine dayalı en popüler seyahat paketlerimizi keşfedin",
    "Multiple Destinations": "Çoklu Destinasyon",
    "Views": "Görüntüleme",
    "Explore": "Keşfet",
    "Car Rental": "Araç Kiralama",
    "Accommodations": "Konaklamalar",
    "City": "Şehir",
    "Select City": "Şehir Seçin",
    "Type": "Tür",
    "Rating": "Değerlendirme",
    "Hotel Apartment": "Apart Otel",
    "Contact for Details": "Detaylar için İletişime Geçin",
    "Tourist Programs": "Turistik Programlar",
    "Tourist Guide": "Turist Rehberi",
    "Discover our latest articles and travel tips": "En son makalelerimizi ve seyahat ipuçlarımızı keşfedin",
    "About Us": "Hakkımızda",
    "Payment Methods": "Ödeme Yöntemleri",
    "Secure, easy, and multiple payment options tailored for you": "Size özel güvenli, kolay ve çoklu ödeme seçenekleri",
    "Secure Checkout": "Güvenli Ödeme",
    "We offer a variety of secure and convenient payment methods to fit your needs, making your booking process smooth and reliable.": "İhtiyaçlarınıza uygun, rezervasyon sürecinizi sorunsuz ve güvenilir hale getiren çeşitli güvenli ve kolay ödeme yöntemleri sunuyoruz.",
    "No payment methods have been added yet.": "Henüz ödeme yöntemi eklenmedi.",
    "100% Secure Payments": "%100 Güvenli Ödemeler",
    "Your payment security is our top priority. We use industry-standard encryption to protect your personal and financial data.": "Ödeme güvenliğiniz en büyük önceliğimizdir. Kişisel ve finansal verilerinizi korumak için endüstri standardı şifreleme kullanıyoruz.",
    "Learn More": "Daha Fazla Bilgi",
    "Happy Clients": "Mutlu Müşteriler",
    "Travel Programs": "Seyahat Programları",
    "Years of Excellence": "Mükemmellik Yılları",
    "Luxury Services": "Lüks Hizmetler"
}

fr_translations = {
    "Customize Your Journey": "Personnalisez Votre Voyage",
    "Destinations": "Destinations",
    "Travelers": "Voyageurs",
    "Services": "Services",
    "Click \"Add City\" to start building your route...": "Cliquez sur \"Ajouter une Ville\" pour commencer à créer votre itinéraire...",
    "Trip Start": "Début du Voyage",
    "Trip End": "Fin du Voyage",
    "Who are you traveling with?": "Avec qui voyagez-vous ?",
    "years": "ans",
    "Please provide children ages": "Veuillez indiquer l'âge des enfants",
    "Custom Services": "Services Personnalisés",
    "Flights": "Vols",
    "Accommodation Style": "Style d'Hébergement",
    "Modern Hotel": "Hôtel Moderne",
    "Family Apartment": "Appartement Familial",
    "Rustic Cottage": "Chalet Rustique",
    "Group Type": "Type de Groupe",
    "Private (VIP)": "Privé (VIP)",
    "Standard Group": "Groupe Standard",
    "Back": "Retour",
    "Next Step": "Étape Suivante",
    "Finish and Send Inquiry": "Terminer et Envoyer la Demande",
    "A travel consultant will reach out via WhatsApp within 24 hours.": "Un consultant en voyages vous contactera via WhatsApp dans les 24 heures.",
    "An error occurred.": "Une erreur s'est produite.",
    "Explore our carefully curated tourist trips": "Découvrez nos voyages touristiques soigneusement sélectionnés",
    "What is included": "Ce qui est inclus",
    "What to bring / Remarks": "Que prévoir / Remarques",
    "Book Now": "Réserver Maintenant",
    "Trip": "Voyage",
    "Featured Programs": "Programmes en Vedette",
    "Discover our most popular travel packages based on customer visits": "Découvrez nos forfaits de voyage les plus populaires en fonction des visites de nos clients",
    "Multiple Destinations": "Destinations Multiples",
    "Views": "Vues",
    "Explore": "Explorer",
    "Car Rental": "Location de Voiture",
    "Accommodations": "Hébergements",
    "City": "Ville",
    "Select City": "Sélectionner une Ville",
    "Type": "Type",
    "Rating": "Évaluation",
    "Hotel Apartment": "Appart hôtel",
    "Contact for Details": "Contactez pour les Détails",
    "Tourist Programs": "Programmes Touristiques",
    "Tourist Guide": "Guide Touristique",
    "Discover our latest articles and travel tips": "Découvrez nos derniers articles et conseils de voyage",
    "About Us": "À Propos de Nous",
    "Payment Methods": "Méthodes de Paiement",
    "Secure, easy, and multiple payment options tailored for you": "Options de paiement sécurisées, faciles et multiples adaptées à vos besoins",
    "Secure Checkout": "Paiement Sécurisé",
    "We offer a variety of secure and convenient payment methods to fit your needs, making your booking process smooth and reliable.": "Nous offrons une variété de méthodes de paiement sécurisées et pratiques pour répondre à vos besoins, rendant votre processus de réservation fluide et fiable.",
    "No payment methods have been added yet.": "Aucune méthode de paiement n'a encore été ajoutée.",
    "100% Secure Payments": "Paiements 100% Sécurisés",
    "Your payment security is our top priority. We use industry-standard encryption to protect your personal and financial data.": "La sécurité de vos paiements est notre priorité absolue. Nous utilisons un cryptage standard pour protéger vos données personnelles et financières.",
    "Learn More": "En Savoir Plus",
    "Happy Clients": "Clients Satisfaits",
    "Travel Programs": "Programmes de Voyage",
    "Years of Excellence": "Années d'Excellence",
    "Luxury Services": "Services de Luxe"
}

def update_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Add new translations
    for k, v in translations.items():
        if k not in data:
            data[k] = v
            
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

update_file('lang/tr.json', tr_translations)
update_file('lang/fr.json', fr_translations)
print("Updated successfully")
